// Code generated by MockGen. DO NOT EDIT.
// Source: business.go
//
// Generated by this command:
//
//	mockgen -source=business.go -destination=../mocks/business.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// SendPaymentNotifications mocks base method.
func (m *MockNotificationService) SendPaymentNotifications(userID int, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPaymentNotifications", userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPaymentNotifications indicates an expected call of SendPaymentNotifications.
func (mr *MockNotificationServiceMockRecorder) SendPaymentNotifications(userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPaymentNotifications", reflect.TypeOf((*MockNotificationService)(nil).SendPaymentNotifications), userID, amount)
}
